// Angular/src/app/app.component.ts
import { Component } from '@angular/core';

import { Customer, Population, Employee, Appointment, Service } from './app.service';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})

export class AppComponent {
  customers: Customer[];
  populationData: Population[];
  employee: Employee;
  positions: string[];
  rules: Object;
  appointmentsData: Appointment[];
  currentDate: Date = new Date(2017, 4, 25);

  constructor(service: Service) {
      this.customers =  service.getCustomers();
      this.populationData = service.getPopulationData();
      this.employee = service.getEmployee();
      this.positions = service.getPositions();
      this.rules = { 'X': /[02-9]/ };
      this.appointmentsData = service.getAppointments();
  }
}
<dx-tab-panel
    [animationEnabled]="true"
    [swipeEnabled]="true">
    <dxi-item title="Data Grid" icon="rowfield">
        <div *dxTemplate>
            <dx-data-grid
                [dataSource]="customers"
                [columns]="['CompanyName', 'City', 'State', 'Phone', 'Fax']">
            </dx-data-grid>
        </div>
    </dxi-item>
    
    <dxi-item title="Chart" icon="chart">
        <div *dxTemplate>
            <dx-chart
                title="World Population by Decade"
                [dataSource]="populationData">
                <dxi-series type="bar"></dxi-series>
            </dx-chart>
        </div>
    </dxi-item>
    
    <dxi-item title="Form" icon="floppy">
        <div *dxTemplate>
            <dx-form
                [colCount]="2"
                [formData]="employee">
                <dxi-item dataField="FirstName" [editorOptions]="{ disabled: true }"></dxi-item>
                <dxi-item dataField="Position" editorType="dxSelectBox" [editorOptions]="{ items: positions, searchEnabled: true, value: '' }">
                    <dxi-validation-rule type="required" message="Position is required"></dxi-validation-rule>
                </dxi-item>
                <dxi-item dataField="LastName" [editorOptions]="{ disabled: true }"></dxi-item>
                <dxi-item dataField="HireDate" editorType="dxDateBox" [editorOptions]="{ value: null, width: '100%' }">
                    <dxi-validation-rule type="required" message="Hire date is required"></dxi-validation-rule>
                </dxi-item>
                <dxi-item dataField="BirthDate" editorType="dxDateBox" [editorOptions]="{ disabled: true, width: '100%' }"></dxi-item>
                <dxi-item dataField="Address"></dxi-item>
                <dxi-item dataField="Notes" editorType="dxTextArea" [editorOptions]="{ height: 90 }" [colSpan]="2"></dxi-item>        
                <dxi-item dataField="Phone" [editorOptions]="{ mask: '+1 (X00) 000-0000', maskRules: rules }"></dxi-item>
                <dxi-item dataField="Email"></dxi-item>        
            </dx-form>
        </div>
    </dxi-item>
    
    <dxi-item title="Scheduler" icon="event" badge="1">
        <div *dxTemplate>
            <dx-scheduler
                [dataSource]="appointmentsData"
                [views]='["week", "month"]'
                currentView="week"
                [currentDate]="currentDate"
                [startDayHour]="9"
                [height]="600">
            </dx-scheduler>
        </div>
    </dxi-item>
</dx-tab-panel>

// Vue/src/App.vue
<template>
  <DxTabPanel>
    <DxItem title="Data Grid" icon="rowfield">
      <template #default>
        <DxDataGrid :data-source="dataSource" :columns="columns" />
      </template>
    </DxItem>

    <DxItem title="Chart" icon="chart">
      <template #default>
        <DxChart
          :data-source="populationData"
          title="World Population by Decade"
        >
          <DxSeries type="bar" />
        </DxChart>
      </template>
    </DxItem>

    <DxItem title="Form" icon="floppy">
      <template #default>
        <DxForm :col-count="2" :form-data="employee">
          <DxSimpleItem
            :editor-options="nameEditorOptions"
            data-field="FirstName"
          />
          <DxSimpleItem
            :editor-options="positionEditorOptions"
            data-field="Position"
            editor-type="dxSelectBox"
          >
            <DxRequiredRule message="Position is required." />
          </DxSimpleItem>
          <DxSimpleItem
            :editor-options="nameEditorOptions"
            data-field="LastName"
          />
          <DxSimpleItem
            :editor-options="hireDateEditorOptions"
            data-field="HireDate"
            editor-type="dxDateBox"
          >
            <DxRequiredRule message="Hire Date is required." />
          </DxSimpleItem>
          <DxSimpleItem
            :editor-options="birthDateEditorOptions"
            data-field="BirthDate"
            editor-type="dxDateBox"
          />
          <DxSimpleItem data-field="Address" />
          <DxSimpleItem
            :col-span="2"
            :editor-options="notesEditorOptions"
            data-field="Notes"
            editor-type="dxTextArea"
          />
          <DxSimpleItem
            :editor-options="phoneEditorOptions"
            data-field="Phone"
          />
          <DxSimpleItem data-field="Email" />
        </DxForm>
      </template>
    </DxItem>

    <DxItem title="Scheduler" icon="event" badge="1">
      <template #default>
        <DxScheduler
          :data-source="schedulerDataSource"
          :current-date="currentDate"
          :views="views"
          :height="600"
          :start-day-hour="9"
          current-view="week"
        />
      </template>
    </DxItem>
  </DxTabPanel>
</template>
<script>
import DxTabPanel, { DxItem } from "devextreme-vue/tab-panel";
import DxDataGrid from "devextreme-vue/data-grid";
import DxChart, { DxSeries } from "devextreme-vue/chart";
import DxForm, { DxSimpleItem, DxRequiredRule } from "devextreme-vue/form";
import DxScheduler from "devextreme-vue/scheduler";

import service from "./data.js";
import "devextreme-vue/text-area";

export default {
  components: {
    DxTabPanel,
    DxItem,
    DxDataGrid,
    DxChart,
    DxSeries,
    DxForm,
    DxSimpleItem,
    DxRequiredRule,
    DxScheduler,
  },
  data() {
    const employee = service.getEmployee();
    const positions = service.getPositions();
    const populationData = service.getPopulationData();
    return {
      dataSource: service.getCustomers(),
      columns: ["CompanyName", "City", "State", "Phone", "Fax"],
      populationData,
      employee,
      positions,
      views: ["week", "month"],
      currentDate: new Date(2017, 4, 25),
      schedulerDataSource: service.getData(),
      nameEditorOptions: { disabled: true },
      positionEditorOptions: {
        value: "",
        searchEnabled: true,
        items: positions,
      },
      hireDateEditorOptions: { value: null, width: "100%" },
      birthDateEditorOptions: { disabled: true, width: "100%" },
      notesEditorOptions: { height: 90 },
      phoneEditorOptions: {
        mask: "+1 (X00) 000-0000",
        maskRules: { X: /[02-9]/ },
      },
    };
  },
};
</script>
<style>
.dx-multiview-item-container {
  padding: 10px;
}
</style>
