// React/src/App.tsx
import './App.css';
import 'devextreme/dist/css/dx.material.blue.light.compact.css';
import TabPanel, { Item } from 'devextreme-react/tab-panel';
import DataGrid from 'devextreme-react/data-grid';
import Chart, { Series } from 'devextreme-react/chart';
import Form, { SimpleItem, RequiredRule } from 'devextreme-react/form';
import Scheduler, { type SchedulerTypes } from 'devextreme-react/scheduler';
import service, {
  type Appointment, type Customer, type Employee, type Population,
} from './data.js';

const columns = ['CompanyName', 'City', 'State', 'Phone', 'Fax'];
const currentDate = new Date(2017, 4, 25);
const views: SchedulerTypes.ViewType[] = ['week', 'month'];

const employee: Employee = service.getEmployee();
const positions: string[] = service.getPositions();
const customers: Customer[] = service.getCustomers();
const appointments: Appointment[] = service.getAppointments();
const populationData: Population[] = service.getPopulationData();
const rules = { X: /[02-9]/ };

const editorOptions = {
  FirstName: { disabled: true },
  Position: {
    items: positions,
    searchEnabled: true,
    value: '',
  },
  LastName: { disabled: true },
  HireDate: { width: '100%', value: null },
  BirthDate: { width: '100%', disabled: true },
  Notes: { height: 90 },
  Phone: {
    mask: '+1 (X00) 000-0000',
    maskRules: rules,
  },
};

function App(): JSX.Element {
  return (
    <div className='main'>
      <TabPanel width={800} animationEnabled={true} swipeEnabled={true}>
        <Item title='Data Grid' icon='rowfield'>
          <DataGrid dataSource={customers} defaultColumns={columns} />
        </Item>
        <Item title='Chart' icon='chart'>
          <Chart title='World Population by Decade' dataSource={populationData}>
            <Series type='bar' />
          </Chart>
        </Item>
        <Item title='Form' icon='floppy'>
          <Form colCount={2} formData={employee}>
            <SimpleItem
              dataField='FirstName'
              editorOptions={editorOptions.FirstName}
            />
            <SimpleItem
              dataField='Position'
              editorType='dxSelectBox'
              editorOptions={editorOptions.Position}
            >
              <RequiredRule message='Position is required.' />
            </SimpleItem>
            <SimpleItem
              dataField='LastName'
              editorOptions={editorOptions.LastName}
            />
            <SimpleItem
              dataField='HireDate'
              editorType='dxDateBox'
              editorOptions={editorOptions.HireDate}
            >
              <RequiredRule message='Hire Date is required.' />
            </SimpleItem>
            <SimpleItem
              dataField='BirthDate'
              editorType='dxDateBox'
              editorOptions={editorOptions.BirthDate}
            />
            <SimpleItem dataField='Address' />
            <SimpleItem
              dataField='Notes'
              colSpan={2}
              editorType='dxTextArea'
              editorOptions={editorOptions.Notes}
            />
            <SimpleItem dataField='Phone' editorOptions={editorOptions.Phone} />
            <SimpleItem dataField='Email' />
          </Form>
        </Item>
        <Item title='Scheduler' icon='event'>
          <Scheduler
            dataSource={appointments}
            views={views}
            defaultCurrentView='week'
            defaultCurrentDate={currentDate}
            height={600}
            startDayHour={9}
          />
        </Item>
      </TabPanel>
    </div>
  );
}

export default App;

// Angular/src/app/app.component.ts
import { Component } from '@angular/core';

import { Customer, Population, Employee, Appointment, Service } from './app.service';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})

export class AppComponent {
  customers: Customer[];
  populationData: Population[];
  employee: Employee;
  positions: string[];
  rules: Object;
  appointmentsData: Appointment[];
  currentDate: Date = new Date(2017, 4, 25);

  constructor(service: Service) {
      this.customers =  service.getCustomers();
      this.populationData = service.getPopulationData();
      this.employee = service.getEmployee();
      this.positions = service.getPositions();
      this.rules = { 'X': /[02-9]/ };
      this.appointmentsData = service.getAppointments();
  }
}
<dx-tab-panel
    [animationEnabled]="true"
    [swipeEnabled]="true">
    <dxi-item title="Data Grid" icon="rowfield">
        <div *dxTemplate>
            <dx-data-grid
                [dataSource]="customers"
                [columns]="['CompanyName', 'City', 'State', 'Phone', 'Fax']">
            </dx-data-grid>
        </div>
    </dxi-item>
    
    <dxi-item title="Chart" icon="chart">
        <div *dxTemplate>
            <dx-chart
                title="World Population by Decade"
                [dataSource]="populationData">
                <dxi-series type="bar"></dxi-series>
            </dx-chart>
        </div>
    </dxi-item>
    
    <dxi-item title="Form" icon="floppy">
        <div *dxTemplate>
            <dx-form
                [colCount]="2"
                [formData]="employee">
                <dxi-item dataField="FirstName" [editorOptions]="{ disabled: true }"></dxi-item>
                <dxi-item dataField="Position" editorType="dxSelectBox" [editorOptions]="{ items: positions, searchEnabled: true, value: '' }">
                    <dxi-validation-rule type="required" message="Position is required"></dxi-validation-rule>
                </dxi-item>
                <dxi-item dataField="LastName" [editorOptions]="{ disabled: true }"></dxi-item>
                <dxi-item dataField="HireDate" editorType="dxDateBox" [editorOptions]="{ value: null, width: '100%' }">
                    <dxi-validation-rule type="required" message="Hire date is required"></dxi-validation-rule>
                </dxi-item>
                <dxi-item dataField="BirthDate" editorType="dxDateBox" [editorOptions]="{ disabled: true, width: '100%' }"></dxi-item>
                <dxi-item dataField="Address"></dxi-item>
                <dxi-item dataField="Notes" editorType="dxTextArea" [editorOptions]="{ height: 90 }" [colSpan]="2"></dxi-item>        
                <dxi-item dataField="Phone" [editorOptions]="{ mask: '+1 (X00) 000-0000', maskRules: rules }"></dxi-item>
                <dxi-item dataField="Email"></dxi-item>        
            </dx-form>
        </div>
    </dxi-item>
    
    <dxi-item title="Scheduler" icon="event" badge="1">
        <div *dxTemplate>
            <dx-scheduler
                [dataSource]="appointmentsData"
                [views]='["week", "month"]'
                currentView="week"
                [currentDate]="currentDate"
                [startDayHour]="9"
                [height]="600">
            </dx-scheduler>
        </div>
    </dxi-item>
</dx-tab-panel>
